ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 9292
    host: "0.0.0.0"
    development: true
postgres:
  url: "jdbc:postgresql://localhost:5433/ktor_tutorial_db"
  user: "postgres"
  password: "123456"
  driver: "org.postgresql.Driver"